--Brogan Avery
--Chapter 6 

--Q1

create sequence customers_customer#_seq
INCREMENT by 1 
start with 1021
nocache
nocycle;

--Q2
insert into customers (customer#, lastname, firstname, zip)
values(CUSTOMERS_CUSTOMER#_SEQ.nextval, 'Shoulders', 'Frank', 23567);

--Q3
CREATE SEQUENCE MY_FIRST_SEQ 
INCREMENT by -3
start with 5
MINVALUE 0
MAXVALUE 5
NOCYCLE;

--Q4
select my_first_seq.nextval from dual;
select my_first_seq.nextval from dual;
select my_first_seq.nextval from dual;
--won't exicute a third time becuase that would drop below 0 which is what the min value is set to. 

--Q5
alter SEQUENCE my_first_seq
minvalue -1000;

--Q6 
create table email_log
(emailid NUMber generated as identity primary key, emaildate date ,customer# number(4));

insert into email_log (emaildate, customer#)
VALUES (sysdate, 1007);

-- cannot leave emailid blank since it is the PK

insert into email_log (emailid, emaildate, customer#)
VALUES (default, sysdate, 1008);

--there is no default value or it is set at null but that won't work because it is the PK
insert into email_log (emailid,emaildate, customer#)
VALUES (25, sysdate, 1009);

--emailid can only be a number generated by the sequence 

--Q7
create synonym numgen 
for my_first_seq;

--Q8
select numgen.nextval 
from dual;

select numgen.currval 
from dual;

drop synonym numgen;

drop sequence my_first_seq;

--Q9
create bitmap index bmp_idx_cust_state on customers(state);

select index_name 
from user_indexes;

drop index bmp_idx_cust_state;

--Q10
create index btree_idx_cust_lname on customers(lastname);

select index_name 
from user_indexes;

drop index btree_idx_cust_lname;

--Q11
create index idx_orderdate_shipdate on orders (orderdate-shipdate);
