# Generated by Django 3.0.6 on 2020-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=400)),
                ('cat', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('action', models.CharField(max_length=400)),
                ('time', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
