# Generated by Django 3.1.7 on 2021-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0002_auto_20210409_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
