# Generated by Django 3.1.7 on 2021-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0003_auto_20210409_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='distancesToOtherLocations',
        ),
    ]
