# Generated by Django 3.0.6 on 2020-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_temps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('region', models.CharField(max_length=400)),
                ('score', models.FloatField()),
            ],
        ),
    ]
