# Generated by Django 3.0.6 on 2020-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400)),
                ('cals', models.IntegerField()),
                ('date', models.CharField(max_length=400)),
            ],
        ),
    ]
