# Generated by Django 3.0.6 on 2020-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20201127_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.CharField(max_length=400),
        ),
    ]
