# Generated by Django 3.0.6 on 2020-11-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element_levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ba', models.FloatField()),
                ('Zr', models.FloatField()),
                ('Sr', models.FloatField()),
                ('Rb', models.FloatField()),
                ('Zn', models.FloatField()),
                ('Ni', models.FloatField()),
                ('Fe', models.FloatField()),
                ('Mn', models.FloatField()),
                ('Ti', models.FloatField()),
                ('Ca', models.FloatField()),
                ('K', models.FloatField()),
            ],
        ),
    ]
